config_version = 2

[bar.default]
capsule = true
center = [ "clock", "date" ]
end = [ "tray", "network", "bluetooth", "volume", "battery", "notifications", "session" ]
margin_edge = 0.0
margin_h = 2
margin_v = 5
radius = 10
reserve_space = true
start = [ "control-center", "workspaces", "media" ]

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 900

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 1077.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

[nightlight]
enabled = true
force = true
temperature_day = 5750
temperature_night = 5700

[noctalia_state]
setup_wizard_completed = true

[shell]
avatar_path = "~/Pictures/profile.jpg"
clipboard_enabled = false
password_style = "random"
polkit_agent = true
settings_show_advanced = false
telemetry_enabled = true

[theme]
builtin = "Tokyo-Night"

[wallpaper]
directory = "~/Pictures/Wallpapers"
enabled = true

    [wallpaper.default]
    path = "~/Pictures/Wallpapers/earthset.jpg"

    [wallpaper.last]
    path = "~/Pictures/Wallpapers/earthset.jpg"

    [wallpaper.monitors.DP-1]
    path = "~/Pictures/Wallpapers/earthset.jpg"

    [wallpaper.monitors.eDP-1]
    path = "~/Pictures/Wallpapers/earthset.jpg"

[weather]
enabled = false

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.control-center]
custom_image = "/usr/share/noctalia/assets/images/distros/cachy.svg"

[widget.date]
enabled = true